# test/testcase_runner.py
import time
import re
from sessiontypes import SESSIONS
from security import SecurityType
from excel_io import ExcelTestCases
RESPONSE_ID=0x18DAF1BA
PHYSICAL_ID=0x18DABAF1
FUNCTIONAL_ID=0x18DBBAF1
def substitute_vars(text, context):
    """Replace variables like $KEY, $SEED."""
    if not text:
        return text
    for k, v in context.items():
        text = text.replace(f"${k}", v)
    return text

def send_request(bus, tester, req):
    data = bytearray(int(x, 16) for x in req.split())
    tester.send_message(data)

def receive_response(collector, timeout=1):
    deadline = time.time() + timeout
    while time.time() < deadline:
        if collector.last_msg:
            msg = collector.last_msg
            if msg is not None:
                collector.last_msg = None
                resp = " ".join(f"{b:02X}" for b in msg.data)
                tokens = resp.split()
            if len(tokens) == 3 and tokens[0] == "7F" and tokens[2] == "78":
                timeout=timeout+5
                continue
            return resp
        time.sleep(0.005)
    return None

def match_response(resp, expected):
    if expected in ("", "*"):
        return
    if expected == "NO RESPONSE":
        if resp is None:
            return
        raise AssertionError(f"Expected no response, got '{resp}'")
    tokens = expected.split()
    regex_parts = []
    for t in tokens:
        if t == "**":
            regex_parts.append(r"[0-9A-F]{2}")
        elif t == "*":
            regex_parts.append(r"([0-9A-F]{2}\s*)*")
        else:
            regex_parts.append(t)
    regex = "^" + r"\s+".join(regex_parts) + "$"
    if not re.fullmatch(regex, resp, flags=re.IGNORECASE):
        raise AssertionError(f"Expected '{expected}', got '{resp}'")

def drain_responses(collector, timeout=0.3):
    """Drain all pending ECU responses before next test."""
    end = time.time() + timeout
    while time.time() < end:
        if collector.last_msg:
            collector.last_msg = None
        time.sleep(0.01)

def do_security_access(ecu, tester, collector, security=None):
    if security is None:
        return
    if ecu.security==security:
        return
    
    def wait_resp():
        return receive_response(collector)
    def send(data_hex: str | list[int]):
        if isinstance(data_hex, str):
            data = [int(x,16) for x in data_hex.split()]
        else:
            data = data_hex
        tester.send_message(data, PHYSICAL_ID)
        return wait_resp()

    resp=send("27 31")
    if resp is None:
        raise TypeError
    if not resp.startswith("67 31"):
        raise ValueError("SecurityAccess: key_TypeX not generated by tester")
    key_msg = tester.generate_sid0x27_0x32_request()
    resp2 = send(" ".join(f"{b:02X}" for b in key_msg))
    if resp2 is None:
        raise TypeError
    if resp2 is None or resp2 != "67 32":
        raise ValueError(f"SecurityAccess: key rejected: {resp2}")
    return

def do_session_switch(ecu, tester, collector, session_name):
    def wait_resp():
        from testcase_runner import receive_response
        r = receive_response(collector)
        return r
    def send(data_hex: str | list[int]):
        if isinstance(data_hex, str):
            data = [int(x,16) for x in data_hex.split()]
        else:
            data = data_hex
        tester.send_message(data, PHYSICAL_ID)
        return wait_resp()

    if session_name is None:
        return

    if session_name == SESSIONS.DEFAULT_SESSION:
        send("10 01")
        return

    elif session_name == SESSIONS.EXTENDED_SESSION:
        send("10 03")
        send("3E 00")    
        return

    elif session_name == SESSIONS.ENGINEERING_SESSION:
        send("10 03")
        send("3E 00")  
        do_security_access(ecu, tester, collector, SecurityType.TYPE_X)
        send("10 04")
        send("3E 00")
        return

    elif session_name == SESSIONS.PROGRAMMING_SESSION:
        send("10 03")
        send("3E 00")
        do_security_access(ecu, tester, collector, SecurityType.TYPE_X)
        resp = send("22 D1 10")
        rid_req = tester.generate_rid0xd111_request() #list[int]
        send(" ".join(f"{b:02X}" for b in rid_req))
        
        resp = send(" ".join(f"{b:02X}" for b in tester.generate_sid0x29_0x05_request()))
        send(" ".join(f"{b:02X}" for b in tester.generate_sid0x29_0x06_request()))
        send("10 02")
        send("3E 00")
        drain_responses(collector)
        return
    else:
        raise ValueError(f"Unknown session: {session_name}")


def run_sequence(seq, bus, collector, tester, excel: ExcelTestCases):
#     tcid = seq["TestCaseID"]
#     final_actual = ""
#     final_result = "PASS"

#     for case in excel.cases:
#         req = case.request
#         expected = case.expected

#         data = bytearray(int(x, 16) for x in req.split())
#         tester.send_message(data)

#         resp = receive_response(collector)
#         final_actual = resp or "NO RESPONSE"

#         try:
#             match_response(resp, expected)
#         except AssertionError:
#             final_result = "FAIL"
#             break

#     excel.write_back(tcid, final_actual, final_result)
#     excel.save()

#     if final_result == "FAIL":
#         raise AssertionError(f"TestCase {tcid} failed")
    return

def run_excel_case(case, bus, collector, ecu, tester, notifier, excel=None):
    # if tester not in notifier.listeners:
    #     notifier.listeners.append(tester)
    req = case.request.strip()
    expected = case.expected.strip()
    address=case.address.strip()
    # session preprocessing
    do_session_switch(ecu, tester, collector, case.session)

    #security access
    do_security_access(ecu, tester, collector, case.security)
 
    # send req
    data = bytearray(int(x,16) for x in req.split())
    arbitration_id = int(address,16)
    tester.send_message(data, arbitration_id)

    # get resp
    resp = receive_response(collector)

    # match
    try:
        match_response(resp, expected)
        excel.write_back(case.tcid, resp or "NO RESPONSE", "PASS")
    except AssertionError:
        excel.write_back(case.tcid, resp or "NO RESPONSE", "FAIL")
    # write back
    # if excel:
    #     excel.write_back(case.tcid, resp or "NO RESPONSE", test_result)