#sessiontypes.py
class SESSIONS:
    DEFAULT_SESSION = 0x01
    PROGRAMMING_SESSION = 0x02
    EXTENDED_SESSION = 0x03
    FOTAINSTALL_SESSION = 0x4C
    FOTAACTIVE_SESSION = 0x4D
    FOTAINSTALLACTIVE_SESSION = 0x4E
    ENGINEERING_SESSION = 0x4F 
    #def __setattr__(self, key, value):
    #    raise AttributeError("DO NOT CHANGE the VALUES of SESSIONS !")

SESSION_NAME_MAP  = {
    SESSIONS.DEFAULT_SESSION: "Default",
    SESSIONS.PROGRAMMING_SESSION: "Programming",
    SESSIONS.EXTENDED_SESSION: "Extended",
    SESSIONS.FOTAINSTALL_SESSION: "FOTA Install",
    SESSIONS.FOTAACTIVE_SESSION: "FOTA Active",
    SESSIONS.FOTAINSTALLACTIVE_SESSION: "FOTA Install Active",
    SESSIONS.ENGINEERING_SESSION: "Engineering",
}