@startuml SID$10
title SID$10
start


    partition SID$10 #LightBlue{
    repeat
    if (、Service $10 リクエスト・メッセージを受信) then (yes)

      partition checkReq #WhiteSmoke{

        if (len(RequestMessage)<2)) then (no) 
            if (diagnosticSessionType legal) then (yes)
                partition checkReqBySession #LightGray{
                    switch(subfunction?)
                        case($01)
                            if(ECU Session legal) then (no)
                                :NRC=$7Eを返送;
                            else(yes)
                                if(len(RequestMessage)!=2)) then (no)
                                    :ECU Session = $01;
                                    :$01を組み込んだポジレスを返送;
                                else(yes)
                                    :NRC=$13を返送; 
                                endif
                            endif 
                        case($02)
                            :...;
                        case($03)
                            if(ECU Session legal) then (no)
                                :NRC=$7Eを返送;
                            else(yes)
                                if(len(RequestMessage)!=2)) then (no)
                                    :ECU Session = $03;
                                    :$03を組み込んだポジレスを返送;
                                else(yes)
                                    :NRC=$13を返送; 
                                endif
                            endif 
                        case($4C)
                            :...;
                        case($4D)
                            :...;
                        case($4E)
                            :...;
                        case($4F)
                            if(ECU Session legal?) then (no)
                                :NRC=$7Eを返送;
                            elseif(Security解除?) then (no)
                                :NRC=$33を返送;
                            else(yes)
                                if(len(RequestMessage)!=2)) then (no)
                                    :ECU Session = $4F;
                                    :$4Fを組み込んだポジレスを返送;
                                else(yes)
                                    :NRC=$13を返送; 
                                endif
                            endif 
                        endswitch
                        :時間リセット;
                }
            else(no)
                :NRC = $12のネガレスを返送;
            endif
        else (yes)
            :NRC = $13のネガレスを返送;
        endif
      }

    else (no)

    endif
    repeat while()
    }
stop
@enduml